Repository mattermost-community/mattermost-plugin-autolink, pull requests merged in 2021-08, with the labels that each got.

#166 [MM-34926] Short-circuit link processing if the regex is non-terminal
  server/autolink/autolink.go
  server/autolink/autolink_test.go
Labels: 4: Reviews Complete

#167 Improve Scope documentation
  README.md
Labels: Docathon 2021

#168 Correct typo in comment in plugin.go
  server/autolinkplugin/plugin.go
Labels: 2: Dev Review
